# Project settings
org.gradle.jvmargs = -Xmx4096M
org.gradle.parallel = true
org.gradle.daemon = false

java_version = 17
pack_format_number = 20

mod_id = dummmmmmy
mod_name = MmmMmmMmmMmm


minecraft_version = 1.20.1
minecraft_min_version = 1.20.1
minecraft_max_version = 1.20.2
enabled_platforms = fabric,forge
mod_license = Supplementaries Team License v.1.5
mod_group_id = net.mehvahdjukaar
mod_authors = MehVahdJukaar, Bonusboni, Plantkillable
mod_credits = MehVahdJukaar, Gooigipunch,Bonusboni, Plantkillable


release_type = release
mod_description = don't hurt me pls :S
mod_homepage = https://www.curseforge.com/minecraft/mmmmmmmmmmmm
mod_github = https://github.com/MehVahdJukaar/DuMmmMmmy/issues

mod_version = 1.20-2.0.11
maven_group = net.mehvahdjukaar
cf_project_id = 225738
mr_project_id =m mmmmmmmmmmm

parchment_version = 1.19.3:2023.03.12
quilt_version = 1.18.2+build.24:v2

modmenu_version = 4.0.0
cloth_version = 7.0.72
mixin_extras_version = 0.2.1-beta.2



fabric_loader_version = 0.16.10
fabric_api_version = 0.92.3+1.20.1

forge_version = 1.20.1-47.4.10
neo_version = 47.1.79
neo_version_range = [47.1,)
loader_version_range = [4,)

# Other deps
moonlight_version = 1.20-2.16.27
moonlight_min_version = 1.20-2.16.19

supplementaries_version = 1.20-3.1.41







