modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dummmmmmy"
version="1.0.0"
displayName="MmmMmmMmmMmm"
credits="bonusboni, Gooigipunch, MCreator"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="MehVahdJukaar,  bonusboni, Gooigipunch"
description='''
don't hurt me pls
'''

[[dependencies.dummmmmmy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




