plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

architectury {
    platformSetupLoomIde()
    forge {
        //platformPackage = "forge"
    }
}


loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        mixinConfig "vista-common.mixins.json"
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}


processResources {
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta', 'update.json']) {
        expand rootProject.ext.replaceProperties + [project: project]
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = "forge"
    atAccessWideners.add("${mod_id}.accesswidener") // this is a path inside the mod jar
}

jar {
    archiveClassifier = "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }

    archiveClassifier = "forge-sources"
}

remapSourcesJar {
    archiveClassifier = "forge-sources"
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.mod_id + "-" + project.name
            from components.java
        }
    }
}


// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }


tasks.withType(JavaCompile).configureEach {
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.output_directory=${new File(rootProject.buildDir, "docsOut")}")
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.multi_source=true")

    it.options.compilerArgs << "-Xmaxerrs" << "4000"

}
dependencies {
    forge "net.minecraftforge:forge:${forge_version}"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    implementation(include("io.github.llamalad7:mixinextras-forge:0.5.0"))

    implementation 'org.jetbrains:annotations:22.0.0'

    //  implementation("net.mehvahdjukaar:moonlight-forge:${moonlight_version}") {
    //     transitive = false
    //  }
    modImplementation "curse.maven:selene-499980:7664875"
    //modImplementation "curse.maven:oculus-581495:6020952"
    //   modImplementation "curse.maven:embeddium-908741:5681725"
    //  modImplementation "curse.maven:supplementaries-412082:7431873"

    //modImplementation("cc.tweaked-cobalt:cobalt:0.93")

    //  modImplementation("cc.tweaked:cc-tweaked-1.21.1-forge:1.117.0")


    //modImplementation("net.mehvahdjukaar:moonlight-forge:${project.moonlight_version}")
    modImplementation ("curse.maven:selene-499980:4806893")
    modImplementation ("curse.maven:apotheosis-313970:4714951")
    modImplementation ("curse.maven:placebo-283644:4711254")
    modImplementation ("curse.maven:apothic-attributes-898963:4721213")
    modImplementation ("curse.maven:champions-unofficial-1074990:5698706")
    modImplementation ("curse.maven:legendary-survival-overhaul-840254:6423363")
    //modImplementation ("curse.maven:configured-457570:4011355")
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    implementation(include("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}"))
    annotationProcessor 'net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5'

}
