name: Build mod

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build mod
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: gradle # Only cache stuff since test build action happen mostly
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -Pnet.minecraftforge.gradle.disableUpdateChecker=true
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MmmMmmMmmMmm
        path: build/libs
